### ISSUE TITLE
info:  TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by robsalasco** [tannerjt/AGStoShapefile#16]
Hi I have problems running this tool on OSX. I'm using this service file

http://www.geoportal.cl/arcgis/rest/services/MinisteriodeMineria/chile_mmin_sernageomin_faenas_mineras/MapServer/0|Faenas_Minera

Can you help me please?

```
robsalasco@galatos:~/AGStoShapefile$ node AGStoSHP.js
(node:54739) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
info: Number of features for service:  1869
info: Getting chunks of 100 features...
info: query -> 0 out of 1869
info: query -> 100 out of 1869
info: query -> 200 out of 1869
info: query -> 300 out of 1869
info: query -> 400 out of 1869
info: query -> 500 out of 1869
info: query -> 600 out of 1869
info: query -> 700 out of 1869
info: query -> 800 out of 1869
info: query -> 900 out of 1869
info: query -> 1000 out of 1869
info: query -> 1100 out of 1869
info: query -> 1200 out of 1869
info: query -> 1300 out of 1869
info: query -> 1400 out of 1869
info: query -> 1500 out of 1869
info: query -> 1600 out of 1869
info: query -> 1700 out of 1869
info: query -> 1800 out of 1869
info: all requests settled
info:  TypeError: Cannot read property '0' of undefined
    at /Users/robsalasco/AGStoShapefile/AGStoSHP.js:123:72
    at _fulfilled (/Users/robsalasco/AGStoShapefile/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/robsalasco/AGStoShapefile/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/robsalasco/AGStoShapefile/node_modules/q/q.js:796:13)
    at /Users/robsalasco/AGStoShapefile/node_modules/q/q.js:604:44
    at runSingle (/Users/robsalasco/AGStoShapefile/node_modules/q/q.js:137:13)
    at flush (/Users/robsalasco/AGStoShapefile/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by robsalasco** [comment]
big data branch works ok!!! thank you!!

**Comment by tannerjt** [comment]
Cool, glad it was able to work!
