### ISSUE TITLE
Type error 

### ISSUE THREAD

**Issue by iskandarblue** [tannerjt/AGStoShapefile#19]
After changing the services in the service.txt file to: 

http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/0

I encounter the following error: 

```
/Users/alexander/Downloads/AGStoShapefile/AGStoSHP.js:64
			requestService(service[0].trim(), service[1].trim(), body.objectIds);
			                                            ^

TypeError: Cannot read property 'trim' of undefined
    at Request._callback (/Users/alexander/Downloads/AGStoShapefile/AGStoSHP.js:64:48)
    at Request.self.callback (/Users/alexander/Downloads/AGStoShapefile/node_modules/request/request.js:186:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/alexander/Downloads/AGStoShapefile/node_modules/request/request.js:1060:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/alexander/Downloads/AGStoShapefile/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:273:16)
    at emitNone (events.js:85:20)
```

Does it having something to do with having no spaces in the url?

**Comment by iskandarblue** [comment]
Just to specify, I would like query about a dozen services, and their URLS are as follows: 


http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/0

http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/1

http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/2

http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/3...

and so on.  Should the script be modified in light of this?

**Comment by tannerjt** [comment]
Hey @iskandarblue, the services.txt file should be formatted with a 'pipe' symbol and a name for the output.  It should look like this:

`http://gis.dallascityhall.com/wwwgis/rest/services/Sdc_public/Zoning/MapServer/0|Deed_Restrictions`

**Comment by tannerjt** [comment]
I juste tested and was able to grab all 827 features
