### ISSUE TITLE
TypeError when running 'node AGStoSHP.js'

### ISSUE THREAD

**Issue by wartickler** [tannerjt/AGStoShapefile#21]
C:\mlc\AGStoShapefile-master>node AGStoSHP.js
util.js:965
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:965:11)
    at Object.<anonymous> (C:\mlc\AGStoShapefile-master\node_modules\objectstream\lib\objectstream.js:43:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\mlc\AGStoShapefile-master\AGStoSHP.js:13:20)

services.txt:
http://services.arcgis.com/ptvDyBs1KkcwzQNJ/arcgis/rest/services/Leon_Buildings/FeatureServer/0|Leon_Buildings
http://services.arcgis.com/ptvDyBs1KkcwzQNJ/arcgis/rest/services/Road_Edge_2012/FeatureServer/0|Road_Edge_2012

**Comment by yipcma** [comment]
i face the same problem

**Comment by LukeSwart** [comment]
I get this error when using node >=7.x. I can verify that this script only works on node 6.x.

**Comment by tannerjt** [comment]
See #25 and solution.  Turns out to be a problem with objectstream.
