### ISSUE TITLE
GDAL took long.

### ISSUE THREAD

**Issue by scaddenp** [tannerjt/AGStoShapefile#29]
I got it to create GeoJson, but getting a message ogr2ogr took longer than 15000 to complete.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ogr2ogr took longer than 15000 to complete
    at Timeout._onTimeout (C:\AGStoShapefile-master\node_modules\ogr2ogr\index.j
s:192:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by tannerjt** [comment]
Did you try running the `bigdata` branch?  It breaks down the requests into smaller files which you can combine after in QGIS or similar.  Right now, it stores the output in memory before writing to a file, which can also cause issues.  This particular issue is happening with a timeout with ogr2ogr.

**Comment by scaddenp** [comment]
No didnt. However, I hacked ogr2ogr to change 15000 to 50000 and it worked.

**Comment by tannerjt** [comment]
Thats great.  Thanks for the fix, I think others will find it helpful.

**Comment by tannerjt** [comment]
For reference, this can be changed here: AGStoShapefile/node_modules/ogr2ogr/index.js:192:31
