### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tjwebb** [tannerjt/AGStoShapefile#36]
node 6.11.3

```
info:  TypeError: Cannot read property '0' of undefined
    at /home/ubuntu/data/acropolis/arcdump/AGStoShapefile/AGStoSHP.js:123:72
    at _fulfilled (/home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:816:13)
    at /home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:624:44
    at runSingle (/home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/data/acropolis/arcdump/AGStoShapefile/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by sandeepgadhwal** [comment]
I am also encountering the same error have you figured out anyway
