### ISSUE TITLE
TypeError: Cannot read property 'sort' of undefined.

### ISSUE THREAD

**Issue by vinura** [tannerjt/AGStoShapefile#46]
C:\Users\Vinura\Documents\OneDrive\Tower Placement Problem QGIS Solution\Data\Geographical Daa\Elevation>agsout -s ./services.txt -o ./
TypeError: Cannot read property 'sort' of undefined
    at requestService (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\index.js:79:11)
    at rp.then (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\index.js:70:4)
    at tryCatcher (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\Vinura\AppData\Roaming\npm\node_modules\agsout\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by tarnh** [comment]
@vinura Please publish the content of your `services.txt` to allow us to debug.

**Comment by andrewteg** [comment]
I recently got this with this line for services.txt:

`https://gismaps.vita.virginia.gov/arcgis/rest/services/VA_Base_layers/VA_Land_Cover/MapServer/0|VA_Base_layers_Land_Cover|500`
