### ISSUE TITLE
ReferenceError: geojsonStream is not defined

### ISSUE THREAD

**Issue by emilyrbowe** [tannerjt/AGStoShapefile#51]
Hi @tannerjt, I'm getting this error when I try to run the package. 

```
ReferenceError: geojsonStream is not defined
    at Timeout.setTimeout (/home/ec2-user/.nvm/versions/node/v6.0.0/lib/node_modules/agsout-modified/index.js:143:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I've modified the chunk size to 1000 instead of 100 and my services.txt is below:
```
https://maps.bexar.org/arcgis/rest/services/Parcels/MapServer/0|parcels|1000
```

Any ideas what's going on? When I run npm list, the geojson-stream package is listed, so I'm not sure what else to try.

Thanks for any suggestions!

**Comment by emilyrbowe** [comment]
Okay, solved this by adding `const geojsonStream = require('geojson-stream');` in line 17 of the `index.js` file and reinstalling the package locally with those modifications. Now bumping into the same issues from #42, so will close this and head over there.
